### ISSUE TITLE
How to setup VSCode?

### ISSUE THREAD

**Issue by adamdry** [corda/vscode-corda#6]
This is directly related to the plugin but how do we setup VSCode for Kotlin development? We need click through to definition for example.

Thanks.

**Comment by anixon604** [comment]
Hi @adamdry , Kotlin support has been very sparse/long time coming to VSCode. It's slowly improving, to click-to-def right now you need to install this extension https://marketplace.visualstudio.com/items?itemName=fwcd.kotlin
