### ISSUE TITLE
Connect to an external node

### ISSUE THREAD

**Issue by jona-sc** [corda/vscode-corda#8]
As a node operator, I want to use the vscode-corda extension to interact with my node running on an external network so that I have access to a simple interface to explore transactions and run queries on it. 

The user should be able to enter access credentials (`hostname`, `port`, `username`, `password`) in order to open an RPC connection to an external node. 

For example, if a customer has a node running on [Chainstack](https://chainstack.com/), they could enter the access credentials to be able to open a connection to it using the vs-code interface:

![chainstack_corda_node](https://user-images.githubusercontent.com/7513603/70876101-4dbd7f80-1ff3-11ea-8b60-fdb4652e6558.png)

**Comment by anixon604** [comment]
@jona-sc I wanted to let you know, vscode-corda and the stand-alone [Node-explorer](https://github.com/corda/node-explorer), now have connect to external node direct or via ssh. :-) appreciate any testing or feedback. enjoy.

**Comment by jona-sc** [comment]
@anixon604 awesome, it works great!

**Comment by DannyRussellWP** [comment]
@anixon604 This is a great feature but when youa re connecting to a remote node how do you specify where the cordapps jars are? Or can it derive them itself? I have connectd but it keeps saying that i need to set the cordapps directory in setting
